/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExampleDiv {
    }
}
declare global {
    interface HTMLExampleDivElement extends Components.ExampleDiv, HTMLStencilElement {
    }
    var HTMLExampleDivElement: {
        prototype: HTMLExampleDivElement;
        new (): HTMLExampleDivElement;
    };
    interface HTMLElementTagNameMap {
        "example-div": HTMLExampleDivElement;
    }
}
declare namespace LocalJSX {
    interface ExampleDiv {
    }
    interface IntrinsicElements {
        "example-div": ExampleDiv;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "example-div": LocalJSX.ExampleDiv & JSXBase.HTMLAttributes<HTMLExampleDivElement>;
        }
    }
}
