on:
  push:
    branches:
      - trunk

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: yarn
      - run: yarn stencil build
      - run: yarn gatsby build --no-uglify --prefix-paths --profile

      - uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: public
